config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, path: 'admin', skip: :registrations

  namespace :admin do
    resources :orders, only: [:index, :show]
    resources :products, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :order_products, only: :show
    resources :users, only: :show
    resources :admin_users, only: [:index, :new, :create, :destroy]

    root to: 'orders#index'
  end

  root 'products#index'

  get 'products,:sort_params' => 'products#index', as: :sorted_products

  put 'orders/:id' => 'orders#complete', as: :complete_order
  get 'orders/:id' => 'orders#show', as: :completed_order

  get 'new_order' => 'orders#start_new_session', as: :new_session

  resources :products, only: [:index, :show] do
    resources :comments, only: :create
  end

  resources :order_products, only: [:create, :update, :destroy]

  resources :carts, only: :index

end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin_user!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include ApplicationHelper

  def after_sign_in_path_for(resource)
    admin_root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    new_admin_user_session_path
  end

  layout :layout

  protected

  def layout
    if devise_controller?
      false
    else
      'application'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end
end

app/views/administrate/application/_sidebar.html.erb
<ul class="sidebar__list">
  <% Administrate::Namespace.new(namespace).resources.each do |resource| %>
  	<% next if resource.name == :users or resource.name == :order_products %>
    <li>
      <%= link_to(
        display_resource_name(resource),
        [namespace, resource.path],
        class: "sidebar__link sidebar__link--#{nav_link_state(resource)}"
      ) %>
    </li>
  <% end %>
  <li style="position: fixed; bottom: 10px">
  	<%= link_to "Logout", destroy_admin_user_session_path, method: :delete, class: "sidebar__list sidebar__link"  %>
  </li>
</ul>