config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, path: 'admin', skip: :registrations

  namespace :admin do
    resources :orders, only: [:index, :show]
    resources :products, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :order_products, only: :show
    resources :users, only: :show
    resources :admin_users, only: [:index, :new, :create, :destroy]

    root to: 'orders#index'
  end

  root 'products#index'

  get 'products,:sort_params' => 'products#index', as: :sorted_products

  put 'orders/:id' => 'orders#complete', as: :complete_order
  get 'orders/:id' => 'orders#show', as: :completed_order

  get 'new_order' => 'orders#start_new_session', as: :new_session

  resources :products, only: [:index, :show] do
    resources :comments, only: :create
  end

  resources :order_products, only: [:create, :update, :destroy]

  resources :carts, only: :index

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :product, required: true
  belongs_to :parent, class_name: 'Comment'
  has_many :children, class_name: 'Comment', foreign_key: 'parent_id'

  validates :content, length: { in: 1..150 }

  scope :from_recent, ->{ order('created_at DESC') }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @product = Product.find(params[:product_id])
    @comments = @product.comments.from_recent
    @comment = @product.comments.new(comment_params)
    @comment.save
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :parent_id, :product_id)
  end
end

app/views/comments/_form.html.erb
<div class="col-1-1">
	<%= form_for comment, remote: true, url: product_comments_path(product_id: product.id), method: 'POST' do |f|  %>
		<% if parent.present? %>
			<%= f.hidden_field :parent_id, value: parent.id %>
		<% end %>
		<%= f.text_field :content, placeholder: 'type your comment', class: 'comment-input'  %>
		<%= f.submit "Save", class: 'submit-btn' %>
	<% end %>
</div>

app/views/comments/_index.html.erb
<% if @comments.count == 0 %>
	<p>No comments here. You will be the first</p>
<% else %>
	<div class="col-1-1 error">
		<% if @comment.present? && @comment.errors.any? %>
			<ul>
			  <% @comment.errors.full_messages.each do |e| %>
			  	<li><%= e %></li>
			  <% end %>
			 </ul>
		<% end %>
	</div>
	<div id="reply" class="col-1-1 reply-comment">
		<%= render 'comments/form', product: @product, comment: @comment, parent: nil %>
	</div>
	<ul>
	<% @comments.each do |comment| %>
		<% if comment.content.present? %>
			<div class="comment-box">
				<i class="fa fa-commenting fa-4x" aria-hidden="true"></i><%= comment.created_at.strftime("%d/%m/%y: %H:%M:%S") %>
			    <li class="comment">
				    <p><%= comment.content %></p>
				    <!-- <button onclick="toggleForm()">Reply</button> -->
				</li>
			</div>
		<% end %>
	<% end %>
	</ul>
<% end %>

<script type="text/javascript">
	function assignProduct(product) {
		product = product;
	}

	document.getElementById("demo").innerHTML = product;

	function toggleForm() {
		document.getElementById('reply').classList.toggle('show');
	}
</script>

app/views/comments/create.js.erb
$(".comments-content").html("<%= escape_javascript(render 'comments/index') %>")