config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, path: 'admin', skip: :registrations

  namespace :admin do
    resources :orders, only: [:index, :show]
    resources :products, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :order_products, only: :show
    resources :users, only: :show
    resources :admin_users, only: [:index, :new, :create, :destroy]

    root to: 'orders#index'
  end

  root 'products#index'

  get 'products,:sort_params' => 'products#index', as: :sorted_products

  put 'orders/:id' => 'orders#complete', as: :complete_order
  get 'orders/:id' => 'orders#show', as: :completed_order

  get 'new_order' => 'orders#start_new_session', as: :new_session

  resources :products, only: [:index, :show] do
    resources :comments, only: :create
  end

  resources :order_products, only: [:create, :update, :destroy]

  resources :carts, only: :index

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_products
  has_one :user
  accepts_nested_attributes_for :user, update_only: true

  enum order_status: %i(completed cart)

  def total_price
    order_products.collect(&:price).sum
  end

  # scope :categorized, ->(names) { where order_status: names.map { |name| Order.order_statuses[name]} }
  scope :categorized, ->(name){ where order_status: name }
end

app/controllers/admin/orders_controller.rb
module Admin
  class OrdersController < Admin::ApplicationController
    # def index
    #   resources = Order.all
    # resources = Order.where(total_price: params[:order_status]).page(params[:page]).per(records_per_page)
    #   page = Administrate::Page::Collection.new(dashboard, order: order)

    #   render locals: {
    #     resources: resources.page(params[:page]).per(records_per_page),
    #     page: page
    #   }
    # end

    # def filter
    #   # resources = Order.categorized(params[:order_status]).page(params[:page]).per(records_per_page)
    #   resources = Order.where(total_price: params[:order_status]).page(params[:page]).per(records_per_page)
    #   page = Administrate::Page::Collection.new(dashboard, order: order)

    #   render locals: {
    #     resources: resources,
    #     page: page
    #   }
    # end

    private

    def resource_params
      params.require(resource_name).permit(dashboard.permitted_attributes.concat(:order_status))
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:complete, :show]

  def complete
    if @order.update(order_params)
    OrderMailer.order_email(@order.user, @order).deliver
      redirect_to completed_order_path
    else
      render :complete
    end
  end

  def show
  end

  def start_new_session
    session[:order_id] = nil
    redirect_to root_path
  end

  private

  def order_params
    params.require(:order).permit(:total_price, :order_status, user_attributes: [:email, :street, :building_nr, :post_code, :city])
  end

  def set_order
    @order = Order.find(params[:id])
  end
end

app/views/orders/_form.html.erb
<h2>Complete your order</h2>
<h4>Where shall we send products for you?</h4>

<%= nested_form_for current_order, url: complete_order_path(current_order.id), method: 'PUT' do |f| %>
	<%= f.hidden_field :total_price, value: current_order.total_price %>
	<%= f.hidden_field :order_status, value: "completed" %>
	<%= f.fields_for :user, User.new do |u| %>
		<div class="row col-1-1 order-form">
			<%= u.label :email, class: 'col-1-2' %>
			<%= u.text_field :email, class: 'col-1-2 user-input' %>

			<%= u.label :street, class: "col-1-2" %>
			<%= u.text_field :street, class: "col-1-2 user-input" %>

			<%= u.label :building_nr, class: "col-1-2" %>
			<%= u.text_field :building_nr, class: "col-1-2 user-input" %>

			<%= u.label :post_code, class: "col-1-2" %>
			<%= u.text_field :post_code, class: "col-1-2 user-input" %>

			<%= u.label :city, class: "col-1-2" %>
			<%= u.text_field :city, class: "col-1-2 user-input" %>
		</div>
	<% end %>
	<div class="row col-1-1 submit-order">
		<%= f.submit "Complete", class: 'submit-btn' %>
	</div>
<% end %>

app/views/orders/complete.html.erb
<div class="col-1-1 error">
  <% if @order.present? && @order.errors.any? %>
  	<ul>
	    <% @order.errors.full_messages.each do |e| %>
	      <li><%= e %></li>
	    <% end %>
	  </ul>
  <% end %>
</div>
<div class="col1-1">
	<%= render 'form', order: @order, user: @user %>
</div>

app/views/orders/show.html.erb
<div class="row order-completed">
	<div class="col-1-1">
		<h2>Your order is completed!</h2>
		<h3>Let us assume everything:</h3>
	</div>
	<div class="col-1-1">
	<h4>You ordered: </h4>
		<% @order.order_products.each do |order_product| %>
			<%= order_product.quantity %>
			<%= order_product.product.name %> - 
			<%= number_to_currency order_product.price %><br/>
		<% end %>
	</div>
	<div class="col-1-1">
	<h4>Your address:</h4>
		<%= @order.user.post_code %> <%= @order.user.city %>,
		<%= @order.user.building_nr %> <%= @order.user.street %>
	</div>
	<div class="col-1-1 kp-shp-btn">
		<%= link_to "Keep shopping", new_session_path %>
	</div>
</div>