config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, path: 'admin', skip: :registrations

  namespace :admin do
    resources :orders, only: [:index, :show]
    resources :products, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :order_products, only: :show
    resources :users, only: :show
    resources :admin_users, only: [:index, :new, :create, :destroy]

    root to: 'orders#index'
  end

  root 'products#index'

  get 'products,:sort_params' => 'products#index', as: :sorted_products

  put 'orders/:id' => 'orders#complete', as: :complete_order
  get 'orders/:id' => 'orders#show', as: :completed_order

  get 'new_order' => 'orders#start_new_session', as: :new_session

  resources :products, only: [:index, :show] do
    resources :comments, only: :create
  end

  resources :order_products, only: [:create, :update, :destroy]

  resources :carts, only: :index

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, presence: true
  validates :description, length: { maximum: 300 }
  validates :price, numericality: { greater_than: 0 }, presence: true

  has_many :order_products

  paginates_per 20

  scope :ordered, ->(sort_params) { order(sort_params) }

  has_many :comments
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < Admin::ApplicationController
    def update
      @product = Product.find(params[:id])
      @product.update(product_params)
      redirect_to admin_products_path
    end

    private

    def product_params
      params.require(:product).permit(:name, :price, :description)
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: :show

  def index
    if params[:sort_params]
      @products = Product.ordered(params[:sort_params])
    else
      @products = Product.all
    end
    @products = @products.page(params[:page])
  end

  def show
    @order_product = current_order.order_products.new
    @comments = @product.comments.from_recent
    @comment = @product.comments.new
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end
end

app/views/products/index.html.erb
<div class="col-1-1">
	<h3 id="marketing-header">Don't you wanna buy something?</h3>
</div> 

<div class="row col-1-1 products-topbar">
	<div class="dropdown">
		<button onclick="toggleDropdown()" class="dropbtn"><b>Sort products</b></button>
		<div id="sort-options" class="dropdown-options">
			<%= link_to 'Lowest price', sorted_products_path('price ASC') %>
			<%= link_to 'Highest price', sorted_products_path('price DESC') %>
			<%= link_to 'Sort by name', sorted_products_path(:name) %>
		</div>
	</div>
</div>

<div class="row">
	<div class="product-index">
		<% @products.each do |product| %>
			<div class="product">
				<%= link_to product.name, product_path(product.id) %>,<br/>
				<%= number_to_currency product.price %><br/>
				<img class="product-img" src="http://www.freeiconspng.com/uploads/photo-video-slr-camera-icon-512x512-pixel-12.png"><br/>
			</div>
		<% end %>
		<div class='products-pagination'>
			<%= paginate @products %>
		</div>
	</div>
</div>

<script type="text/javascript">
	function toggleDropdown() {
		document.getElementById("sort-options").classList.toggle("show");
	}
</script>

app/views/products/show.html.erb
<div class="row">
  <div class="col-2-3 product-details">
      <h3><b><%= @product.name %></b></h3>
      <h4>Price: <%= number_to_currency @product.price %></h4>
      <%= form_for @order_product, remote: true do |f| %>
        <i class="fa fa-cart-plus fa-2x" aria-hidden="true"></i>
        <%= f.number_field :quantity, value: 1,  min: 1, class: 'quantity-input' %>
        <%= f.hidden_field :product_id, value: @product.id %>
        <%= f.submit "Add to Cart", class: 'submit-btn' %>
      <% end %>
      <p class="product-description"><%= @product.description %></p>
  </div>
  <div class="col-1-3">
    <img style="width: 100%;" src="http://www.freeiconspng.com/uploads/photo-video-slr-camera-icon-512x512-pixel-12.png">
  </div>
</div>
<div class="row">
  <h3 class="col-1-1">What customers say about <%= @product.name %>?</h3>
  <div class="col-2-3">
    <%= render 'comments/form', product: @product, comment: @comment, parent: nil %>
  </div>
  <div class="col-1-3"></div>
  <div class="col-2-3 comments-content">
    <%= render 'comments/index' %>
  </div>
</div>